- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Import VPC Variables
      include_vars:
        file: vars/vpc_setup.yml  # Ensure this is the correct path with the .yml extension

    - name: Debug variables (Optional: to verify if variables are loaded)
      debug:
        msg: "VPC Name: {{ vpc_name }}, CIDR Block: {{ vpccidr }}, Region: {{ region }}"

    - name: Create vprofiles VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpccidr }}"
        region: "{{ region }}"
        enable_dns_support: true
        enable_dns_hostnames: true
        tenancy: "default"
        state: "{{ state }}"
      register: vpc_info
