- hosts: localhost
  connection: local
  gather_facts: no  # Fixed from "gather_fact"

  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create vprofiles VPC
      ec2_vpc_net:  
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpccidr }}"
        region: "{{ region }}"
        enable_dns_support: yes
        enable_dns_hostnames: yes
        tenancy: "default"
        state: "{{ state }}"
      register: vpc_out
      #